name = "Δ_st"
run_count = 1

[data_file]
row_labels = 1
column_labels = 1

[run_settings]
graph_degree = 100
value_offset = 0.4
value_scaling = 1e+4
tolerance = 1e-5

[[separator_configs]]
inequality = "Δ"
maxcut = 400

[[separator_configs]]
inequality = "ST"
maxcut = 400
