name = "all"
run_count = 3

[[separators]]
inequality = "Î”"
variable_once = false
maxcut = 400

[[separators]]
inequality = "ST"
heuristic = 1
maxcut = 400

[[separators]]
inequality = "ST"
heuristic = 2
maxcut = 400

[[separators]]
inequality = "cycle"
type = "half-chorded"
maxcut = 400
time_limit = 900

[[separators]]
inequality = "cycle"
type = "two-chorded"
maxcut = 400
time_limit = 900
